-- ADDS CENTROIDS COLUMN AND CREATES THE SPATIAL POINT DATA
--  FOR BOTH THE OUTPUT AREA DATA AND THE STORES DATA

-- FIRST THE OUTPUT AREAS
ALTER TABLE `_PROJECT_._DATASET_.OA21_CENTROIDS` 
    ADD COLUMN IF NOT EXISTS centroid GEOGRAPHY;

UPDATE `_PROJECT_._DATASET_.OA21_CENTROIDS`
    SET centroid = ST_GEOGPOINT(longitude,latitude) WHERE true;


-- AND NOW THE STORES
ALTER TABLE `_PROJECT_._DATASET_.stores` 
    ADD COLUMN IF NOT EXISTS geom GEOGRAPHY;

UPDATE `_PROJECT_._DATASET_.stores`
    SET geom = ST_GEOGPOINT(longitude,latitude) WHERE true;

