-- CREATES A NEW KMEANS MODEL
CREATE OR REPLACE MODEL _DATASET_.KMean10_10Clusters_OAandPop_Std_KPP
  OPTIONS(model_type='kmeans', 
          NUM_CLUSTERS=10,
          STANDARDIZE_FEATURES = TRUE,
          KMEANS_INIT_METHOD = 'KMEANS++') AS
SELECT * EXCEPT (Store) FROM `_PROJECT_._DATASET_.K10Raw`
