-- CONFLATE THE TABLES INTO A SINGLE PVT_CONFLATED TABLE
--  USING THE GEOGRAPHY CODE FOR THE JOIN
CREATE OR REPLACE TABLE _PROJECT_._DATASET_.PVT_Conflated AS
SELECT
  T1.*,
  T2.* EXCEPT(Output_Areas),
  T3.* EXCEPT(Output_Areas),
  T4.* EXCEPT(Output_Areas),
  T5.* EXCEPT(Output_Areas),
  T6.* EXCEPT(date, geography, geography_code)    -- THE TABLE LOADED DIRECT FROM NOMIS
FROM
  _DATASET_.PVT_TS001_Residents AS T1    -- THE BASE TABLE

-- THE TABLES BELOW ARE JOINED TO THE BASE TABLE
JOIN
  _DATASET_.PVT_TS044 AS T2
ON
  T1.Output_Areas = T2.Output_Areas
JOIN
  _DATASET_.PVT_TS062 AS T3
ON
  T1.Output_Areas = T3.Output_Areas
JOIN
  _DATASET_.PVT_TS063 AS T4
ON
  T1.Output_Areas = T4.Output_Areas
JOIN
  _DATASET_.PVT_TS066 AS T5
ON
  T1.Output_Areas = T5.Output_Areas
JOIN
  _DATASET_.TS007 AS T6
ON
  T1.Output_Areas = T6.geography_code;
